spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flairstech-education
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 50MB
springdoc:
  default-produces-media-type: application/json
application:
  file:
    uploads:
      photos-output-path: ./uploads
server:
  servlet:
    context-path: /api/v1/


