spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flairstech-education
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/
